// ──────────────────────────────────────────────────────────
// Nominalization Map — curated noun → verb/simpler-form mappings
// These enable deterministic reversal WITHOUT introducing new information.
// E.g. "the implementation of X was performed" → "X was implemented"
// NOT → "We implemented X" (introduces "we" not in original)
// ──────────────────────────────────────────────────────────

/** Map of nominalized noun → base verb form */
export const NOMINALIZATION_MAP: Record<string, string> = {
  // Common academic nominalizations
  'implementation': 'implement',
  'implementations': 'implement',
  'utilization': 'use',
  'utilisation': 'use',
  'determination': 'determine',
  'identification': 'identify',
  'investigation': 'investigate',
  'examination': 'examine',
  'evaluation': 'evaluate',
  'observation': 'observe',
  'classification': 'classify',
  'characterization': 'characterize',
  'characterisation': 'characterise',
  'optimization': 'optimize',
  'optimisation': 'optimise',
  'fabrication': 'fabricate',
  'preparation': 'prepare',
  'calculation': 'calculate',
  'measurement': 'measure',
  'estimation': 'estimate',
  'formulation': 'formulate',
  'demonstration': 'demonstrate',
  'verification': 'verify',
  'validation': 'validate',
  'modification': 'modify',
  'transformation': 'transform',
  'application': 'apply',
  'accumulation': 'accumulate',
  'approximation': 'approximate',
  'assessment': 'assess',
  'assumption': 'assume',
  'collection': 'collect',
  'comparison': 'compare',
  'completion': 'complete',
  'composition': 'compose',
  'computation': 'compute',
  'consideration': 'consider',
  'construction': 'construct',
  'consumption': 'consume',
  'contribution': 'contribute',
  'conversion': 'convert',
  'deformation': 'deform',
  'degradation': 'degrade',
  'derivation': 'derive',
  'description': 'describe',
  'detection': 'detect',
  'development': 'develop',
  'dissolution': 'dissolve',
  'distribution': 'distribute',
  'elimination': 'eliminate',
  'establishment': 'establish',
  'extraction': 'extract',
  'generation': 'generate',
  'incorporation': 'incorporate',
  'indication': 'indicate',
  'integration': 'integrate',
  'interpretation': 'interpret',
  'introduction': 'introduce',
  'isolation': 'isolate',
  'migration': 'migrate',
  'nucleation': 'nucleate',
  'oxidation': 'oxidize',
  'precipitation': 'precipitate',
  'prediction': 'predict',
  'production': 'produce',
  'propagation': 'propagate',
  'provision': 'provide',
  'purification': 'purify',
  'quantification': 'quantify',
  'realization': 'realize',
  'recognition': 'recognize',
  'recommendation': 'recommend',
  'reconstruction': 'reconstruct',
  'reduction': 'reduce',
  'regulation': 'regulate',
  'removal': 'remove',
  'representation': 'represent',
  'requirement': 'require',
  'selection': 'select',
  'separation': 'separate',
  'simulation': 'simulate',
  'specification': 'specify',
  'stabilization': 'stabilize',
  'substitution': 'substitute',
  'synthesis': 'synthesize',
  'variation': 'vary',
  'visualization': 'visualize',
};

/**
 * Reverse-map: given a nominalized noun, return the verb form.
 * Returns null if no mapping exists.
 */
export function getNominalizationVerb(noun: string): string | null {
  return NOMINALIZATION_MAP[noun.toLowerCase()] ?? null;
}
